steps:
#- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - test-build-trigger
  - --region=us-central1
  - --source=.
  - --trigger-http
  - --runtime=nodejs18